//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.18020.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class node {
    
    private string naamschool_1Field;
    
    private string lidnrField;
    
    private string fipfnrField;
    
    private string profielField;
    
    private string genderField;
    
    private string emailschool_2Field;
    
    private string countryField;
    
    private string bvlfMemberStatusField;
    
    private string subscriptionDateField;
    
    private string subscriptionExpirationField;
    
    private string telschool_1Field;
    
    private string naamField;
    
    private string voornaamField;
    
    private string busschool_1Field;
    
    private string straatField;
    
    private string straatschool_1Field;
    
    private string nrSchool_1Field;
    
    private string nrField;
    
    private string busField;
    
    private string zipcodeschool_1Field;
    
    private string postcodeField;
    
    private string plaatsschool_1Field;
    
    private string emailschool_1Field;
    
    private string plaatsField;
    
    private string telField;
    
    private string naamschool_2Field;
    
    private string straatschool_2Field;
    
    private string mobileField;
    
    private string nrschool_2Field;
    
    private string busschool_2Field;
    
    private string zipcodeschool_2Field;
    
    private string plaatsschool_2Field;
    
    private string telschool_2Field;
    
    private string idField;
    
    private string versionField;
    
    private string parentIDField;
    
    private string levelField;
    
    private string writerIDField;
    
    private string nodeTypeField;
    
    private string templateField;
    
    private string sortOrderField;
    
    private string createDateField;
    
    private string updateDateField;
    
    private string nodeNameField;
    
    private string urlNameField;
    
    private string writerNameField;
    
    private string nodeTypeAliasField;
    
    private string pathField;
    
    private string loginNameField;
    
    private string emailField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string naamschool_1 {
        get {
            return this.naamschool_1Field;
        }
        set {
            this.naamschool_1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string lidnr {
        get {
            return this.lidnrField;
        }
        set {
            this.lidnrField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string fipfnr {
        get {
            return this.fipfnrField;
        }
        set {
            this.fipfnrField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string profiel {
        get {
            return this.profielField;
        }
        set {
            this.profielField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string gender {
        get {
            return this.genderField;
        }
        set {
            this.genderField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string emailschool_2 {
        get {
            return this.emailschool_2Field;
        }
        set {
            this.emailschool_2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string country {
        get {
            return this.countryField;
        }
        set {
            this.countryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string bvlfMemberStatus {
        get {
            return this.bvlfMemberStatusField;
        }
        set {
            this.bvlfMemberStatusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string subscriptionDate {
        get {
            return this.subscriptionDateField;
        }
        set {
            this.subscriptionDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string subscriptionExpiration {
        get {
            return this.subscriptionExpirationField;
        }
        set {
            this.subscriptionExpirationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string telschool_1 {
        get {
            return this.telschool_1Field;
        }
        set {
            this.telschool_1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string naam {
        get {
            return this.naamField;
        }
        set {
            this.naamField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string voornaam {
        get {
            return this.voornaamField;
        }
        set {
            this.voornaamField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string busschool_1 {
        get {
            return this.busschool_1Field;
        }
        set {
            this.busschool_1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string straat {
        get {
            return this.straatField;
        }
        set {
            this.straatField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string straatschool_1 {
        get {
            return this.straatschool_1Field;
        }
        set {
            this.straatschool_1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string nrSchool_1 {
        get {
            return this.nrSchool_1Field;
        }
        set {
            this.nrSchool_1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string nr {
        get {
            return this.nrField;
        }
        set {
            this.nrField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string bus {
        get {
            return this.busField;
        }
        set {
            this.busField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string zipcodeschool_1 {
        get {
            return this.zipcodeschool_1Field;
        }
        set {
            this.zipcodeschool_1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string postcode {
        get {
            return this.postcodeField;
        }
        set {
            this.postcodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string plaatsschool_1 {
        get {
            return this.plaatsschool_1Field;
        }
        set {
            this.plaatsschool_1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string emailschool_1 {
        get {
            return this.emailschool_1Field;
        }
        set {
            this.emailschool_1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string plaats {
        get {
            return this.plaatsField;
        }
        set {
            this.plaatsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string tel {
        get {
            return this.telField;
        }
        set {
            this.telField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string naamschool_2 {
        get {
            return this.naamschool_2Field;
        }
        set {
            this.naamschool_2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string straatschool_2 {
        get {
            return this.straatschool_2Field;
        }
        set {
            this.straatschool_2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string mobile {
        get {
            return this.mobileField;
        }
        set {
            this.mobileField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string nrschool_2 {
        get {
            return this.nrschool_2Field;
        }
        set {
            this.nrschool_2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string busschool_2 {
        get {
            return this.busschool_2Field;
        }
        set {
            this.busschool_2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string zipcodeschool_2 {
        get {
            return this.zipcodeschool_2Field;
        }
        set {
            this.zipcodeschool_2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string plaatsschool_2 {
        get {
            return this.plaatsschool_2Field;
        }
        set {
            this.plaatsschool_2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string telschool_2 {
        get {
            return this.telschool_2Field;
        }
        set {
            this.telschool_2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string parentID {
        get {
            return this.parentIDField;
        }
        set {
            this.parentIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string level {
        get {
            return this.levelField;
        }
        set {
            this.levelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string writerID {
        get {
            return this.writerIDField;
        }
        set {
            this.writerIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string nodeType {
        get {
            return this.nodeTypeField;
        }
        set {
            this.nodeTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string template {
        get {
            return this.templateField;
        }
        set {
            this.templateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string sortOrder {
        get {
            return this.sortOrderField;
        }
        set {
            this.sortOrderField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string createDate {
        get {
            return this.createDateField;
        }
        set {
            this.createDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string updateDate {
        get {
            return this.updateDateField;
        }
        set {
            this.updateDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string nodeName {
        get {
            return this.nodeNameField;
        }
        set {
            this.nodeNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string urlName {
        get {
            return this.urlNameField;
        }
        set {
            this.urlNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string writerName {
        get {
            return this.writerNameField;
        }
        set {
            this.writerNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string nodeTypeAlias {
        get {
            return this.nodeTypeAliasField;
        }
        set {
            this.nodeTypeAliasField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string path {
        get {
            return this.pathField;
        }
        set {
            this.pathField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string loginName {
        get {
            return this.loginNameField;
        }
        set {
            this.loginNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string email {
        get {
            return this.emailField;
        }
        set {
            this.emailField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class NewDataSet {
    
    private node[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("node")]
    public node[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}
