//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bvlf_v2.BOL.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bvlf_org_v2Entities : DbContext
    {
        public bvlf_org_v2Entities()
            : base("name=bvlf_org_v2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<StudieDagSubscription> StudieDagSubscriptions { get; set; }
        public DbSet<StudieDagSubscriptions_Sessions> StudieDagSubscriptions_Sessions { get; set; }
        public DbSet<cmsContentXml> cmsContentXmls { get; set; }
        public DbSet<cmsMember> cmsMembers { get; set; }
    }
}
