//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bvlf_v2.BOL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class cmsContentXml
    {
        public int nodeId { get; set; }
        public string xml { get; set; }
    
        public virtual cmsMember cmsMember { get; set; }
    }
}
