//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bvlf_v2.BOL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudieDagSubscriptions_Sessions
    {
        public int SubscriptionSessionId { get; set; }
        public int SubscriptionId { get; set; }
        public int SessionId { get; set; }
    
        public virtual StudieDagSubscription StudieDagSubscription { get; set; }
    }
}
